import type {
  CaseDetail,
  Comment,
  Customer,
  Transaction,
  TransactionDetail,
} from "./api-types";

// Fixed transaction details matching the API spec and alert payload
export const MOCK_TRANSACTION_DETAILS: TransactionDetail = {
  account_balance: 10000,
  account_id: "acc_789",
  account_type: "SAVINGS",
  acquiring_bankname: "Sample Bank",
  acquiring_country: "US",
  card_masked: true,
  card_number: "411111******1111",
  card_type: "CREDIT",
  count_txn_id_1d: 5,
  counter_partyid: "cp_303",
  courier_fingerprint: "cour_fp_505",
  courierid: "cour_404",
  customer_fingerprint: "fp_789",
  customer_id: "cust_456",
  customer_name: "John Doe",
  device_appcloned: false,
  device_id: "dev_101",
  device_ip: "192.168.1.1",
  device_iplocation: "US",
  device_mockgps: false,
  device_vpnactive: false,
  event_type: "FT",
  issuing_bankname: "Issuing Bank",
  issuing_country: "US",
  merchant_addresscity: "San Francisco",
  merchant_addresscountry: "US",
  merchant_addressdistrict: "Downtown",
  merchant_addressline1: "123 Main St",
  merchant_addresslocality: "San Francisco",
  merchant_addresspostalcode: "94105",
  merchant_addressstate: "CA",
};

// Fixed customers data
export const FIXED_CUSTOMERS: Customer[] = [
  {
    id: 2001,
    name: "John Smith",
    email: "john.smith@example.com",
    dob: "15-06-1985",
    phoneNumber: "+1-555-0123",
    accountId: 3001,
    createdAt: Date.now() - 365 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
  {
    id: 2002,
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    dob: "23-09-1990",
    phoneNumber: "+1-555-0124",
    accountId: 3002,
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
  },
  {
    id: 2003,
    name: "Michael Chen",
    email: "michael.chen@example.com",
    dob: "07-12-1988",
    phoneNumber: "+1-555-0125",
    accountId: 3003,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 2004,
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    dob: "30-03-1992",
    phoneNumber: "+1-555-0126",
    accountId: 3004,
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 2005,
    name: "David Brown",
    email: "david.brown@example.com",
    dob: "18-11-1987",
    phoneNumber: "+1-555-0127",
    accountId: 3005,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
];

// Fixed transactions for each case with more variety
export const FIXED_TRANSACTIONS: Record<number, Transaction[]> = {
  1001: [
    {
      id: "TXN1001001",
      amount: 1250.0,
      currencyCode: "USD",
      status: "SUSPICIOUS",
      type: "Purchase",
      fraudSeverity: "High",
      scenarioName: "Unusual Location",
      channel: "POS",
      country: "US",
      createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
      details: { ...MOCK_TRANSACTION_DETAILS, device_iplocation: "RU" },
    },
    {
      id: "TXN1001002",
      amount: 750.0,
      currencyCode: "USD",
      status: "SUSPICIOUS",
      type: "Purchase",
      fraudSeverity: "High",
      scenarioName: "Multiple Attempts",
      channel: "Online",
      country: "IN",
      createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
      details: { ...MOCK_TRANSACTION_DETAILS, count_txn_id_1d: 15 },
    },
  ],
  1002: [
    {
      id: "TXN1002001",
      amount: 45.0,
      currencyCode: "USD",
      status: "GENUINE",
      type: "Purchase",
      fraudSeverity: "Low",
      scenarioName: "-",
      channel: "Online",
      country: "US",
      createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
      details: MOCK_TRANSACTION_DETAILS,
    },
  ],
  1003: [
    {
      id: "TXN1003001",
      amount: 1200.0,
      currencyCode: "USD",
      status: "SUSPICIOUS",
      type: "Withdrawal",
      fraudSeverity: "High",
      scenarioName: "Large Withdrawal",
      channel: "ATM",
      country: "MX",
      createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
      details: { ...MOCK_TRANSACTION_DETAILS, account_balance: 1500 },
    },
    {
      id: "TXN1003002",
      amount: 50.0,
      currencyCode: "USD",
      status: "SUSPICIOUS",
      type: "Purchase",
      fraudSeverity: "Medium",
      scenarioName: "Unusual Time",
      channel: "Online",
      country: "US",
      createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
      details: MOCK_TRANSACTION_DETAILS,
    },
  ],
  1004: [
    {
      id: "TXN1004001",
      amount: 5000.0,
      currencyCode: "EUR",
      status: "SUSPICIOUS",
      type: "Transfer",
      fraudSeverity: "High",
      scenarioName: "International Transfer",
      channel: "Online",
      country: "FR",
      createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
      details: { ...MOCK_TRANSACTION_DETAILS, device_vpnactive: true },
    },
  ],
  1005: [
    {
      id: "TXN1005001",
      amount: 100.0,
      currencyCode: "USD",
      status: "GENUINE",
      type: "Purchase",
      fraudSeverity: "Low",
      scenarioName: "False Positive",
      channel: "Mobile",
      country: "US",
      createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
      details: MOCK_TRANSACTION_DETAILS,
    },
  ],
};

// Fixed comments for each case
export const FIXED_COMMENTS: Record<number, Comment[]> = {
  1001: [
    {
      id: 1,
      authorId: 101,
      header: "Investigation",
      content:
        "Multiple high-value transactions from unusual locations detected. IP address traced to known VPN service.",
      createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    },
    {
      id: 2,
      authorId: 101,
      header: "Customer Contact",
      content:
        "Customer contacted and confirmed they are traveling abroad. However, some transactions were not recognized.",
      createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    },
  ],
  1002: [
    {
      id: 3,
      authorId: 102,
      header: "Note",
      content:
        "Small value transaction flagged due to unusual pattern. Requires further investigation.",
      createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    },
  ],
  1003: [
    {
      id: 4,
      authorId: 102,
      header: "Investigation",
      content:
        "Large ATM withdrawal followed by multiple small online purchases. Typical money mule pattern.",
      createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    },
  ],
  1004: [
    {
      id: 5,
      authorId: 103,
      header: "Resolution",
      content:
        "Case confirmed as fraudulent. Customer's card has been blocked and new card issued.",
      createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    },
  ],
  1005: [
    {
      id: 6,
      authorId: 104,
      header: "Resolution",
      content:
        "Transaction pattern matches customer's normal behavior. Case closed as false positive.",
      createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
      updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    },
  ],
};

// Fixed cases data
export const FIXED_CASES: CaseDetail[] = [
  {
    id: 1001,
    entityId: 5001,
    customerId: 2001,
    parentAlertId: 3001,
    status: "IN_PROGRESS",
    priority: "High",
    assignedTo: 101,
    age: "6d",
    resolutionType: undefined,
    linkedCases: [{ id: 1002, linkedAt: Date.now() - 5 * 24 * 60 * 60 * 1000 }],
    createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 1002,
    entityId: 5002,
    customerId: 2002,
    parentAlertId: 3002,
    status: "NEW",
    priority: "Medium",
    assignedTo: undefined,
    age: "5d",
    resolutionType: undefined,
    linkedCases: [],
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 1003,
    entityId: 5003,
    customerId: 2003,
    parentAlertId: 3003,
    status: "ESCALATED",
    priority: "High",
    assignedTo: 102,
    age: "3d",
    resolutionType: undefined,
    linkedCases: [{ id: 1001, linkedAt: Date.now() - 2 * 24 * 60 * 60 * 1000 }],
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 60 * 60 * 1000,
  },
  {
    id: 1004,
    entityId: 5004,
    customerId: 2004,
    parentAlertId: 3004,
    status: "RESOLVED",
    priority: "Medium",
    assignedTo: 103,
    age: "10d",
    resolutionType: "Confirmed Fraud",
    linkedCases: [],
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 1005,
    entityId: 5005,
    customerId: 2005,
    parentAlertId: 3005,
    status: "CLOSED",
    priority: "Low",
    assignedTo: 104,
    age: "15d",
    resolutionType: "False Positive",
    linkedCases: [],
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
];
